---
- name: learning to recall var data
  hosts: localhost
  connection: local
  
  var:
           telecom:
                    - ericsson
                    - alu
                    - avaya
                    - cisco 
           heroes:
                     marvel:
                             - spiderman
                             - ironman
                             - daredevil
                     dc:
                             - woderwoman
                             - batman
                             - superman
  tasks:
           - name: print out spiderman
		     debug:
			        msg: "{{ heroes }}"
					
           - name: print out batman
                                	     debug:

                                   msg: "{{XYZ}}"		
					
            - name: print out ALL dc heroes
                                	     debug:

                                  msg: "{{XYZ}}"	
					
             - name: print out cisco
                                  debug:
                                        msg: "{{XYZ}}"
                                        
             - name: print out ALL dc AND marvel heroes
                                  debug:
                                   msg: "{{XYZ}}"		
