---
 - name: Our first play
   hosts: planetexpress
   tasks:
           
     - name: Install steam locomotive an All machines
       apt: 
         name: sl
         state: present
       become: yes # run as sudo
